
* What it is?
This is a code to scrape the Moneycontrol & generate the datebase for
the NSE Stocks. The Database will have all the financial info of all
the NSE listed stocks. 

The purpose for this code is to get all the stocks & its financial
databse for future use & immune to parent website changes. This is
going to make web scraping unnecessary.

* How it is? 

Will have a python script for this task that will scrape the
moneycontrol website. Next it will go through each of the financial
pages like income statement, balance sheet, cash flow statement, key
ratios & make a xls file for the same.

* Planned tasks [1/3]

- [X] plan the activities
- [-] make the python script
  - [X] pull financials from moneycontrol
    - [X] income statement
    - [X] balance sheet
    - [X] cash flow
    - [X] key ratios
  - [-] save to xls with pages
    - [X] print the data pulled from moneycontrol
    - [ ] format as items in first columns & year descending as top row
    - [ ] format cell width
- [-] run script to generate xls for each stock listed in NSE
  - [X] read in data from existing csv file
  - [X] capture by industry
  - [ ] run for all industries

